FROM neomediatech/ubuntu-base:24.04

ENV SERVICE=fail2ban \
    APP_VERSION=1.0.2

LABEL maintainer="docker-dario@neomediatech.it" \ 
      org.label-schema.version=$APP_VERSION \
      org.label-schema.vcs-type=Git \
      org.label-schema.vcs-url=https://github.com/Neomediatech/${SERVICE} \
      org.label-schema.maintainer=Neomediatech

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends --no-install-suggests \
                    python3 python3-pip \
                    wget ipset iptables ssmtp redis-tools curl whois ca-certificates jq && \
    python3 -m pip install pyasynchat --break-system-packages && \
    rm -rf /var/lib/apt/lists* && \
    mkdir -p /var/run/fail2ban && \
    cd /tmp && \
    if [[ "$APP_VERSION" == "latest" ]]; then \
	TAG=""; \
    else \
	TAG="tags/"; \
    fi && \
    APP_VERSION="$(basename $(curl -s https://api.github.com/repos/fail2ban/fail2ban/releases/${TAG}${APP_VERSION} | jq -r '.tag_name'))" && \
    wget https://github.com/fail2ban/fail2ban/releases/download/${APP_VERSION}/fail2ban_${APP_VERSION}-1.upstream1_all.deb && \
    dpkg -i fail2ban_${APP_VERSION}-1.upstream1_all.deb && \
    cd / && \
    rm -rfv /tmp/* /etc/fail2ban/jail.d/*

    
COPY entrypoint.sh /entrypoint.sh

RUN chmod a+x /entrypoint.sh

VOLUME [ "/data" ]

ENTRYPOINT [ "/tini", "--", "/entrypoint.sh" ]
CMD [ "fail2ban-server", "-f", "-x", "-v", "start" ]

HEALTHCHECK --interval=30s --timeout=5s CMD fail2ban-client ping
