FROM neomediatech/ubuntu-base:22.04

ENV SERVICE=fail2ban \
    APP_VERSION=1.0.2

LABEL maintainer="docker-dario@neomediatech.it" \ 
      org.label-schema.version=$APP_VERSION \
      org.label-schema.vcs-type=Git \
      org.label-schema.vcs-url=https://github.com/Neomediatech/${SERVICE} \
      org.label-schema.maintainer=Neomediatech

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends --no-install-suggests \
                    libexpat1 libmpdec3 libpython3-stdlib libpython3.10-minimal libpython3.10-stdlib \
                    libreadline8 libsqlite3-0 media-types python3 python3-minimal python3.10 python3.10-minimal \
                    readline-common wget ipset iptables ssmtp redis-tools curl whois ca-certificates && \
    rm -rf /var/lib/apt/lists* && \
    rm -rf /etc/fail2ban/jail.d && \
    mkdir -p /var/run/fail2ban && \
    cd /tmp && \
    wget https://github.com/fail2ban/fail2ban/releases/download/1.0.1/fail2ban_${APP_VERSION}-1.upstream1_all.deb && \
    dpkg -i fail2ban_${APP_VERSION}-1.upstream1_all.deb && \
    cd / && \
    #mkdir -p /usr/local/etc/fail2ban && \
    #cp -rp /etc/fail2ban /usr/local/etc && \
    rm -rfv /tmp/*

    
COPY entrypoint.sh /entrypoint.sh

RUN chmod a+x /entrypoint.sh

VOLUME [ "/data" ]

ENTRYPOINT [ "/tini", "--", "/entrypoint.sh" ]
CMD [ "fail2ban-server", "-f", "-x", "-v", "start" ]

HEALTHCHECK --interval=30s --timeout=5s CMD fail2ban-client ping
